name: QPM publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version
        id: version
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          VERSION="${GITHUB_REF#refs/tags/v}"

          echo "tag=$TAG" | tee -a "$GITHUB_OUTPUT"
          echo "version=$VERSION" | tee -a "$GITHUB_OUTPUT"

      - name: Setup qpm
        uses: fernthedev/qpm-action@v1
        with:
          workflow_token: ${{ secrets.GITHUB_TOKEN }}
          restore: false
          resolve_ndk: false
          cache: false
          publish: "late"
          publish_token: ${{ secrets.QPM_TOKEN }}
          version: "${{ steps.version.outputs.version}}"
          tag: "${{ steps.version.outputs.tag}}"

      - name: Create a release using action-github-release
        uses: softprops/action-gh-release@v2
        with:
          name: "${{ steps.version.outputs.tag }}, mmkay?"
          tag_name: "${{ steps.version.outputs.tag}}"
          draft: false
          generate_release_notes: true
          files: |
            shared/mmkay.cmake
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
